packages:
  - "apps/*"
  - "server"
allowBuilds:
  '@google/genai': true
  '@prisma/engines': true
  msgpackr-extract: true
  prisma: true
  protobufjs: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - expo-image@57.0.3
